from pathlib import Path
import re
import unittest


ROOT = Path(__file__).resolve().parents[1]
GODOT_ANDROID = ROOT / "godot-android"
HARNESS = GODOT_ANDROID / "tests" / "proxy_targets_live_harness.gd"
RUNNER = ROOT / "tools" / "run_proxy_targets_live_harness.ps1"
MANUAL_RUNNER = ROOT / "tools" / "run_proxy_targets_live_manual_check.ps1"


class GodotProxyTargetsLiveHarnessTests(unittest.TestCase):
    def test_non_xr_harness_runs_as_headless_scene_tree_script(self):
        self.assertTrue(HARNESS.exists())
        source = HARNESS.read_text(encoding="utf-8")

        self.assertIn("extends SceneTree", source)
        self.assertIn('PROXY_TARGETS_CONSUMER_SCRIPT', source)
        self.assertIn('PROXY_TARGETS_CARD_ADAPTER_SCRIPT', source)
        self.assertIn('FileAccess.get_file_as_string', source)
        self.assertIn('GDScript.new()', source)
        self.assertIn('script.source_code = source', source)
        self.assertIn('script.reload()', source)
        self.assertIn('_load_script_from_env("PROXY_TARGETS_CONSUMER_SCRIPT"', source)
        self.assertIn('_load_script_from_env("PROXY_TARGETS_CARD_ADAPTER_SCRIPT"', source)
        self.assertNotIn('preload("res://scripts/proxy_targets_consumer.gd")', source)
        self.assertNotIn('preload("res://scripts/proxy_targets_card_adapter.gd")', source)
        self.assertIn("WebSocketPeer.new()", source)
        self.assertIn("_connect_attempts", source)
        self.assertIn("_last_connect_error", source)
        self.assertIn("connect_to_url(_ws_url)", source)
        self.assertIn("_ws.poll()", source)
        self.assertRegex(source, re.compile(r"func _process\(delta: float\).*?\n\t_connect_ws\(\).*?\n\t_ws\.poll\(\)", re.S))
        self.assertNotIn("WebSocketPeer.STATE_CLOSED", source)
        self.assertIn("JSON.parse_string", source)
        self.assertIn("apply_proxy_targets_message", source)
        self.assertIn("FileAccess.open(_status_res, FileAccess.WRITE)", source)
        self.assertIn('"packets": _packets', source)
        self.assertIn('"depth_source": _last_depth_source', source)
        self.assertIn('"depth_confidence": _last_depth_confidence', source)
        self.assertIn('"ws_state": _ws.get_ready_state()', source)
        self.assertIn('"connect_attempts": _connect_attempts', source)
        self.assertIn('"last_connect_error": _last_connect_error', source)
        self.assertIn('"parsed": _parsed', source)
        self.assertIn('"live": _live', source)
        self.assertIn("quit(0)", source)
        self.assertIn("quit(1)", source)

        self.assertNotIn("OpenXR", source)
        self.assertNotIn("XRServer", source)
        self.assertNotIn("XROrigin", source)

    def test_non_xr_harness_uses_fake_card_wrapper_adapter_contract(self):
        source = HARNESS.read_text(encoding="utf-8")

        self.assertIn("class HarnessCardWrapper", source)
        self.assertIn("func register_node3d_target(target_id: String, node_or_path) -> bool:", source)
        self.assertIn("func attach_to_target(card_id: String, target_id: String, offset_rule = {}) -> bool:", source)
        self.assertIn("var registered_targets := {}", source)
        self.assertIn("var attachments := {}", source)
        self.assertIn("_adapter.bind(_consumer, _card_wrapper)", source)
        self.assertNotIn("\nadapter.bind(_consumer, _card_wrapper)", source)
        self.assertIn("_card_wrapper.registered_targets.size()", source)
        self.assertIn("_card_wrapper.attachments.size()", source)

    def test_live_harness_runner_uses_stripped_temp_project_without_gxr(self):
        self.assertTrue(RUNNER.exists())
        source = RUNNER.read_text(encoding="utf-8")

        self.assertTrue(source.lstrip().startswith("param("))
        self.assertIn(r"E:\xia\Godot_v4.6.2-stable_win64.exe\Godot_v4.6.2-stable_win64.exe", source)
        self.assertIn("godot-android", source)
        self.assertIn(".tmp", source)
        self.assertIn("proxy_targets_live_harness_project", source)
        self.assertIn(".ProviderPath", source)
        self.assertIn('Join-Path -Path $RepoRoot -ChildPath ".tmp\\proxy_targets_live_harness_project"', source)
        self.assertIn("Build-HarnessProject", source)
        self.assertIn("Ensure-GodotUserLogsDir", source)
        self.assertIn("app_userdata", source)
        self.assertIn("proxy_targets_live_harness", source)
        self.assertIn("Write-HarnessProjectFile", source)
        self.assertIn("Assert-PathUnderRepo", source)
        self.assertIn("[switch]$PrepareOnly", source)
        self.assertIn("[switch]$ScriptOnly", source)
        self.assertIn("[string]$StatusFile = \"\"", source)
        self.assertIn("if ($PrepareOnly)", source)
        self.assertIn("Copy-Item", source)
        self.assertIn("scripts\\proxy_targets_consumer.gd", source)
        self.assertIn("scripts\\proxy_targets_card_adapter.gd", source)
        self.assertIn("tests\\proxy_targets_live_harness.gd", source)
        self.assertIn("config/name=\"proxy_targets_live_harness\"", source)
        self.assertIn("proxy_targets_live_harness.gd", source)
        self.assertIn("--headless", source)
        self.assertIn("--script", source)
        self.assertIn("$ProjectHarnessScriptPath = Join-Path -Path $ProjectDir -ChildPath \"tests\\proxy_targets_live_harness.gd\"", source)
        self.assertIn("PROXY_TARGETS_CONSUMER_SCRIPT", source)
        self.assertIn("PROXY_TARGETS_CARD_ADAPTER_SCRIPT", source)
        self.assertIn("if ($ScriptOnly)", source)
        self.assertIn("& $GodotExe --headless --log-file $GodotLogFile --script $ScriptPath", source)
        self.assertIn("& $GodotExe --headless --log-file $GodotLogFile --path $ProjectDir --script $ProjectHarnessScriptPath", source)
        self.assertIn("PROXY_TARGETS_WS_URL", source)
        self.assertIn("PROXY_TARGETS_REQUIRE", source)
        self.assertIn("PROXY_TARGETS_TIMEOUT_SEC", source)
        self.assertIn("PROXY_TARGETS_STATUS_RES", source)
        self.assertIn("Status file: $StatusFullPath", source)
        self.assertIn("godot_harness.log", source)
        self.assertIn("--log-file", source)
        self.assertNotIn("set_gxr_extension.ps1", source)
        self.assertNotIn("-Mode disable", source)
        self.assertNotIn("-Mode enable", source)
        self.assertNotIn("addons\\gxr_sdk", source)
        self.assertNotIn("extension_list.cfg", source)
        self.assertIn("try {", source)
        self.assertIn("finally {", source)

    def test_manual_live_check_script_runs_publisher_and_bounded_headless_harness(self):
        self.assertTrue(MANUAL_RUNNER.exists())
        source = MANUAL_RUNNER.read_text(encoding="utf-8")

        self.assertTrue(source.lstrip().startswith("param("))
        self.assertIn("run_godot_script_only_staged_probe.ps1", source)
        self.assertIn("script_only_staged_probe", source)
        self.assertIn("-Stage", source)
        self.assertIn("apply", source)
        self.assertIn("-StartPort", source)
        self.assertIn("Start-Process", source)
        self.assertIn("-WindowStyle Hidden", source)
        self.assertIn("RedirectStandardOutput", source)
        self.assertIn("RedirectStandardError", source)
        self.assertIn(".tmp", source)
        self.assertIn("proxy_targets_live_manual_check", source)
        self.assertIn(".ProviderPath", source)
        self.assertIn('Join-Path -Path $RepoRoot -ChildPath ".tmp\\proxy_targets_live_manual_check"', source)
        self.assertIn("WaitForExit", source)
        self.assertIn("$GateProcess.Refresh()", source)
        self.assertIn("$null -eq $ExitCode", source)
        self.assertIn("$StatusText = Get-Content -LiteralPath $StageStatusFile -Raw", source)
        self.assertIn("$Status = $StatusText | ConvertFrom-Json", source)
        self.assertIn('$Require -eq "packets"', source)
        self.assertIn('$Require -eq "parsed"', source)
        self.assertIn("$Status.live", source)
        self.assertIn("$RequirementMet", source)
        self.assertIn("Staged apply raw gate exit code:", source)
        self.assertIn("Final validation exit code:", source)
        self.assertNotIn("Staged apply gate exit code:", source)
        self.assertIn("Kill()", source)
        self.assertIn("finally {", source)
        self.assertIn("script_only_websocket_staged_probe_status.json", source)
        self.assertNotIn("run_proxy_targets_live_harness.ps1", source)
        self.assertNotIn("OpenXR", source)
        self.assertNotIn("XRServer", source)
        self.assertNotIn("addons\\gxr_sdk", source)


if __name__ == "__main__":
    unittest.main()
